version: '2'
checks:
  argument-count:
    enabled: true
  method-complexity:
    enabled: true
  return-statements:
    enabled: true
  duplication:
    enabled: true

engines:
  eslint:
    enabled: true
  duplication:
    enabled: true

ratings:
  paths:
    - "src/**/*.js"
    - "src/**/*.jsx"
    - "*.js"
    - "*.jsx"

exclude_paths:
  - "node_modules/"
  - "build/"
  - "dist/"
  - "coverage/"
  - "public/"
